# Generated by Django 2.2.3 on 2019-07-12 12:59

import authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'constraints': [],
                'indexes': [],
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', authentication.managers.PersonManager()),
            ],
        ),
    ]
